apiVersion: apps/v1
kind: Deployment

metadata:
  name: task-management-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: task-management-api

  template:
    metadata:
      labels:
        app: task-management-api

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: task-management-api

      containers:
        - name: task-management-api
          image: ghcr.io/valinfernanda/task-management-api:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20