apiVersion: v1
kind: Service

metadata:
  name: task-management-api

spec:
  selector:
    app: task-management-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: LoadBalancer
  